### ISSUE TITLE
Same values for redundancy and synergy 

### ISSUE THREAD

**Issue by perevo** [robince/partial-info-decomp#5]
I used calc_pi_mvn to calculate the pid for two continuous stimuli and meg signals. The results return the same values for redundancy and synergy.
Are there any tips or examples for this situation?

**Comment by robince** [comment]
Are your variables Gaussian? Did you first use "copnorm" from my GCMI package? Are the values actually numerically equal (same floating point) or just similar values? Bit difficult to help more without an example. If the interaction information / co-information is zero (can be checked outside of PID by linear combination of standard MI values, e.g. calculated using GCMI) then since coInfo = Red - Syn they should have the same value.

**Comment by perevo** [comment]
Yes, the variables were transformed by "copnorm" before the pid calculation. I will check the interaction information according to your suggestion. Thanks.

**Comment by robince** [comment]
You can calculate coinformation with:
I(A; MEG) + I(B; MEG) - I([A B]; MEG)
Postive terms indicate net redundancy, negative terms net synergy in the system. 

If this is zero then it requires that Red=Syn in the PID. What the PID results then show is that although there is no overall / net interaction, there are redundant and synergistic interactions that cancel out.
